# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f874b7e0f999dfe5940dbe02628e25df0f7399abbd807a5f4b30a96a0fedae8fa854d441e8c24c3e565a4f3d086d20f70c37ad5355599078abbd12ea4974a5c

test:
  secret_key_base: 5108e4cb6f8d38466bfb55229e8485f345e828dbb0aadb7ffc9a5a901a4f34d61a486d8c0c1c64baf2976a76902f2b00e7cc2c76cd56b7d18ea259184e5c0dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
